CREATE TABLE `ngLog` (
  `reqTime` DATETIME NOT NULL,
  `ip` VARCHAR(16) NOT NULL,
  `url` VARCHAR(1024) NOT NULL,
  `status` VARCHAR(8) NOT NULL,
  `browser` VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
